site_name: Fake CG Wiki
docs_dir: srcs
site_dir: docs
site_url: https://neilkleistgao.github.io/fake-CG-wiki/
strict: false

theme:
  name: material
  language: 'zh'
  include_search_page: false
  palette:
    primary: black
    accent: blue
  features:
    - navigation.tabs
    - navigation.top
extra:
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''

extra_css:
  - '_static/css/extra.css?v=13'

extra_javascript:
  - '_static/js/extra.js?v=16'
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 简介:
    - Getting Started: index.md
    - 关于本项目: intro/about.md
    - 致谢: intro/thanks.md
  - 工具软件:
    - 工具软件简介: tools/index.md
    - IDE: tools/ide.md
    - OpenGL: tools/opengl.md
    - Unity3D: tools/unity3d.md
    - Blender: tools/blender.md
    - 也许……: tools/none.md
  - 线性代数:
    - 线性代数简介: linear_algebra/index.md
    - 向量: linear_algebra/vector.md
    - 矩阵: linear_algebra/matrix.md
    - 向量空间: linear_algebra/vector_space.md
    - 基和维数: linear_algebra/base.md
  - 微积分:
    - 微积分简介: calculus/index.md
    - 从自然数说起: calculus/natural.md
    - 柯西数列与极限: calculus/sequence.md
    - 函数极限，求导和微分: calculus/derivative.md
    - 介值定理和微分中值定理: calculus/mean.md
    - 积分和牛顿-莱布尼茨公式: calculus/integration.md
    - 复数和欧拉公式: calculus/complex.md
    - 常用积分方法: calculus/integration2.md
    - 偏导数和偏微分: calculus/pd.md
    - 多重积分: calculus/mi.md
  - 概率论:
    - 概率论简介: probabiity/index.md
    - 古典概型: probabiity/classical.md
    - 几何概型: probabiity/geometry.md
    - 期望: probabiity/expect.md
  - 光栅化:
    - 光栅化简介: rasterization/index.md
    - 渲染管线: rasterization/pipeline.md
    - MVP变换: rasterization/mvp.md
    - 光栅化: rasterization/rasterization.md
    - 深度缓存: rasterization/zbuffer.md
    - 基本光照模型: rasterization/shading.md
    - 纹理映射: rasterization/texture.md
  - 光线追踪:
    - 光线追踪简介: ray_tracing/index.md
    - Whitted光线追踪: ray_tracing/whitted.md
    - 加速结构: ray_tracing/struct.md
    - 路径追踪: ray_tracing/path.md
  - 反走样技术:
    - 反走样技术简介: antialiasing/index.md
    - 采样原理: antialiasing/sampling.md
    - 多重采样抗锯齿: antialiasing/msaa.md
    - MIPMAP: antialiasing/mipmap.md
  - 几何建模:
    - 几何建模简介: geometry/index.md
  - 基于物理的渲染:
    - 基于物理的渲染简介: pbr/index.md
    - 辐射度量学: pbr/radiance.md
    - 渲染方程与BRDF: pbr/equation.md
  - 实时渲染技术:
    - 实时渲染简介: rtr/index.md
  - 非真实感渲染:
    - 非真实感渲染简介: npr/index.md
  - 光子映射:
    - 光子映射简介: photon/index.md
  - 杂项:
    - 简介: misc/index.md
    - Gamma校正: misc/gamma.md
    - 相机与透镜: misc/lens.md
    - 颜色空间: misc/color.md